apiVersion: apps/v1
kind: Deployment
metadata:
  name: corrector-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corrector
  template:
    metadata:
      labels:
        app: corrector
    spec:
      containers:
        - name: corrector
          image: us.gcr.io/ticketing-dev-311118/corrector
---
# Cluster IP Service
apiVersion: v1
kind: Service
metadata:
  name: corrector-srv
spec:
  selector:
    app: corrector
  ports:
    - name: corrector
      protocol: TCP
      port: 3000
      targetPort: 3000